import { Router, type IRouter } from "express";
import healthRouter from "./health";
import campaignsRouter from "./campaigns";
import campaignUpdatesRouter from "./campaign-updates";
import campaignImagesRouter from "./campaign-images";
import campaignExpensesRouter from "./campaign-expenses";
import campaignEvidenceRouter from "./campaign-evidence";
import campaignTransparencyRouter from "./campaign-transparency";
import donationsRouter from "./donations";
import newsRouter from "./news";
import testimonialsRouter from "./testimonials";
import statsRouter from "./stats";
import contactRouter from "./contact";
import volunteersRouter from "./volunteers";
import adminRouter from "./admin";
import communityReportsRouter from "./community-reports";
import petsRouter from "./pets";
import alliesRouter from "./allies";
import dashboardRouter from "./dashboard";
import faqRouter from "./faq";
import adminUsersRouter from "./admin-users";
import settingsRouter from "./settings";
import sitemapRouter from "./sitemap";
import uploadsRouter from "./uploads";

const router: IRouter = Router();

router.use(healthRouter);
router.use(campaignsRouter);
router.use(campaignUpdatesRouter);
router.use(campaignImagesRouter);
router.use(campaignExpensesRouter);
router.use(campaignEvidenceRouter);
router.use(campaignTransparencyRouter);
router.use(donationsRouter);
router.use(newsRouter);
router.use(testimonialsRouter);
router.use(statsRouter);
router.use(contactRouter);
router.use(volunteersRouter);
router.use(adminRouter);
router.use(communityReportsRouter);
router.use(petsRouter);
router.use(alliesRouter);
router.use(dashboardRouter);
router.use(faqRouter);
router.use(adminUsersRouter);
router.use(settingsRouter);
router.use(sitemapRouter);
router.use(uploadsRouter);

export default router;
